@startuml C4_Elements!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.pumlLAYOUT_LEFT_RIGHTPerson_Ext(visitorAlias, "Visitor", "Person interested in Charity")Person(editorAlias, "Editor", "Person who works for Charity")System_Ext(cmsAlias, "ExpressionEngine", "PHP CMS (LAMP)")Person_Ext(agencyAlias, "Incumbent", "Agency")Rel(visitorAlias, cmsAlias, "Visits", "HTTP")Rel(editorAlias, agencyAlias, "Request Feature", "EMAIL")Rel(agencyAlias, cmsAlias, "Adds Features", "GIT")Rel(editorAlias, cmsAlias, "Edits", "HTTP")@enduml