@startuml C4_Elements!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.pumlLAYOUT_LEFT_RIGHTPerson_Ext(visitorAlias, "Visitor", "Person interested in Charity")Person(editorAlias, "Editor", "Person who works for Charity")Person(devAlias, "Developer", "Full Stack Developer")System_Ext(vercelAlias, "Vercel", "Content Delivery Network")System_Ext(cmsAlias, "DatoCMS", "Content Management System")System_Ext(pipedreamAlias, "PipeDream", "Event Sourcing")System_Boundary(c1, "GitHub") {    Container(nextjsAlias, "Web App", "Next.js", "React/TypeScript")}Rel(visitorAlias, vercelAlias, "Uses", "HTTP")Rel(devAlias, nextjsAlias, "Commit", "GIT")Rel(editorAlias, cmsAlias, "Edits", "HTTP")Rel(cmsAlias, vercelAlias, "Triggers Build", "HTTP")Rel(pipedreamAlias, vercelAlias, "Triggers Build", "HTTP")Rel(vercelAlias, cmsAlias, "Fetches Content", "HTTP/GraphQL")Rel(c1, vercelAlias, "Deploys", "GitHub Action")@enduml